# Generated by Django 4.2.4 on 2023-09-07 13:04

from django.db import migrations, models
import django.db.models.deletion
import purchaseairtime.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_alter_members_unique_together'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransactions',
            fields=[
                ('transactionId', purchaseairtime.models.TransactionID(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTransactions',
            fields=[
                ('transactionId', purchaseairtime.models.TransactionID(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.group')),
            ],
        ),
    ]
